// File generated by FlutterFire CLI (manually created)
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVBApwjZn4OSgON5Ja36n5-PLQUigbjY4',
    appId: '1:381838704656:android:aaa0ddbf1692003ee88a95',
    messagingSenderId: '381838704656',
    projectId: 'poetry-world-eaf6c',
    storageBucket: 'poetry-world-eaf6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrIHJkk6mLJECzfJfJQ7BZ9L7F8K8K8K8',
    appId: '1:381838704656:ios:aaa0ddbf1692003ee88a96',
    messagingSenderId: '381838704656',
    projectId: 'poetry-world-eaf6c',
    storageBucket: 'poetry-world-eaf6c.firebasestorage.app',
    iosClientId: '381838704656-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.techhikes.poetryApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVBApwjZn4OSgON5Ja36n5-PLQUigbjY4',
    appId: '1:381838704656:web:aaa0ddbf1692003ee88a97',
    messagingSenderId: '381838704656',
    projectId: 'poetry-world-eaf6c',
    authDomain: 'poetry-world-eaf6c.firebaseapp.com',
    storageBucket: 'poetry-world-eaf6c.firebasestorage.app',
  );
}
